// Menü görselleri take-away-system'den indirildi (public/images/menu).
// Anahtar = menu.ts içindeki ürün adı (birebir).
export const productImages: Record<string, string> = {
  "Az Mercimek": "/images/menu/suzme-mercimek-corbasi.jpg",
  "Süzme Mercimek": "/images/menu/suzme-mercimek-corbasi.jpg",
  "Yayla Çorbası": "/images/menu/yayla-corbasi.webp",
  "Adana Kebap": "/images/menu/adana-kebap.webp",
  "Urfa Kebap": "/images/menu/urfa-kebap.webp",
  "Patlıcanlı Kebap": "/images/menu/patlicanli-kebap.webp",
  "Domatesli Kebap": "/images/menu/domatesli-kebap.webp",
  "Karışık Kebap": "/images/menu/karisik-kebap.webp",
  "Beyti": "/images/menu/beyti.webp",
  "Fırın Beyti": "/images/menu/firin-beyti.webp",
  "Köfte": "/images/menu/kofte.webp",
  "Konak Köfte": "/images/menu/konak-kofte.webp",
  "Tavuk Şiş": "/images/menu/tavuk-sis.webp",
  "Et Şiş": "/images/menu/et-sis.webp",
  "Kanat": "/images/menu/kanat.webp",
  "Kanat Yaprak": "/images/menu/kanat-yaprak.webp",
  "Tavuk Göğüs": "/images/menu/tavuk-gogus.webp",
  "Tavuk Pirzola": "/images/menu/tavuk-pirzola.webp",
  "Ciğer": "/images/menu/ciger.webp",
  "Ali Nazik Kebabı": "/images/menu/ali-nazik-kebabi.webp",
  "Konak Kebap Spesiyali": "/images/menu/konak-kebap-spesiyali.webp",
  "Adana İskender": "/images/menu/adana-i-skender.webp",
  "Yoğurtlu Kebap": "/images/menu/yogurtlu-kebap.webp",
  "Altı Ezmeli Kebap": "/images/menu/alti-ezmeli-kebap.webp",
  "Çiğköfte Porsiyon": "/images/menu/cigkofte-porsiyon.webp",
  "Adana Dürüm": "/images/menu/adana-durum.webp",
  "Urfa Dürüm": "/images/menu/urfa-durum.webp",
  "Tavuk Şiş Dürüm": "/images/menu/tavuk-sis-durum.webp",
  "Et Şiş Dürüm": "/images/menu/et-sis-durum.webp",
  "Ciğer Dürüm": "/images/menu/ciger-durum.webp",
  "Fırın Dürüm": "/images/menu/firin-durum.webp",
  "Lahmacun": "/images/menu/lahmacun.webp",
  "Fındık Lahmacun": "/images/menu/findik-lahmacun.webp",
  "Kaşarlı Lahmacun": "/images/menu/kasarli-lahmacun.webp",
  "Sebzeli Pide": "/images/menu/sebzeli-pide.webp",
  "Kaşarlı Pide": "/images/menu/kasarli-pide.webp",
  "Kıymalı Kaşarlı Pide": "/images/menu/kiymali-kasarli-pide.webp",
  "Kuşbaşı Kaşarlı Pide": "/images/menu/kusbasi-kasarli-pide.webp",
  "Sucuklu Kaşarlı Pide": "/images/menu/sucuklu-kasarli-pide.webp",
  "Kavurmalı Kaşarlı Pide": "/images/menu/kavurmali-kasarli-pide.webp",
  "Karışık Pide": "/images/menu/karisik-pide.webp",
  "Kanat (500 gr.)": "/images/menu/kanat-500gr.webp",
  "Kilo Köfte (500 gr.)": "/images/menu/kilo-kofte-500-gr.webp",
  "Kilo Kanat": "/images/menu/kilo-kanat.webp",
  "Kilo Köfte": "/images/menu/kilo-kofte.webp",
  "Kilo Pirzola": "/images/menu/kilo-pirzola.webp",
  "Sütlaç": "/images/menu/sutlac.webp",
  "Künefe": "/images/menu/kunefe.webp",
  "Katmer": "/images/menu/katmer.webp",
  "Su": "/images/menu/su.webp",
  "Ayran": "/images/menu/ayran.webp",
  "Ayran 1 Lt": "/images/menu/ayran-1-lt.webp",
  "Sade Soda": "/images/menu/sade-soda.webp",
  "Meyveli Soda": "/images/menu/meyveli-soda.webp",
  "Gazoz": "/images/menu/gazoz.webp",
  "Şalgam": "/images/menu/salgam.webp",
  "Ice Tea": "/images/menu/ice-tea.webp",
  "Meyve Suyu": "/images/menu/meyve-suyu.webp",
  "Kola / Yedigün": "/images/menu/kola-yedigun.webp",
  "Kola 1 Lt": "/images/menu/kola-1-lt.webp",
  "Kola 2.5 Lt": "/images/menu/kola-2-5-lt.webp",
};
